// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales = 'en' | 'ru'

export type Translation = {
  /**
   * Frontend Template
   */
  title: string
  /**
   * User count: {{count}}
   */
  userCount: string
  landingShort: {
    /**
     * Productivity systems fail.
     */
    headline: string
    /**
     * Todorant works.
     */
    headline2: string
    /**
     * Focus on one task at a time
     */
    feature1: string
    /**
     * Always add a date or a month to a task
     */
    feature2: string
    /**
     * Complete unpleasant tasks (frogs) first
     */
    feature3: string
    /**
     * Keep your inbox empty
     */
    feature4: string
    /**
     * What's the difference?
     */
    differenceTitle: string
    /**
     * All other productivity apps focus on storing, organizing and automating endless lists of tasks. Todorant focuses on the only thing that matters: it makes you complete the tasks.
     */
    differenceText1: string
    /**
     * Todorant uses a carefully crafted set of limits and praise to punish bad behaviour and support good habits. It affects the primitive part of the brain to make it crave completing todos like people crave sugar.
     */
    differenceText2: string
    /**
     * I've read and tried 20+ productivity books and methodologies. When all of them failed one by one I combined their components and simplified the result. This is how Todorant was created.
     */
    differenceText3: string
    /**
     * Truly cross-platform
     */
    crossplatform: string
    /**
     * What's the deal?
     */
    dealTitle: string
    /**
     * Todorant is free for the first 30 days and then it is $5/month. It is more expensive than competitors because it works. If you don't get $5 worth of productivity in the first 30 days of the free trial, you are welcome not to continue to use Todorant.
     */
    dealText1: string
    /**
     * No strings attached. You don't need to give us any information like a credit card at all before your trial ends. You don't even need an account if you install the mobile apps!
     */
    dealText2: string
    /**
     * The only exception is if you signup on iOS, Apple has forced us to make you commit to a free trial before you can use the app. The way to avoid this limit is to create an account here, on the website, and then log in on the iOS app.
     */
    dealText3: string
    /**
     * Act!
     */
    act: string
    contact: {
      /**
       * Still got questions? Contact me directly at
       */
      '0': string
      /**
       * . Thank you.
       */
      '1': string
    }
    /**
     * Privacy policy
     */
    privacy: string
  }
  /**
   * Sign in
   */
  signIn: string
  menu: {
    darkMode: {
      /**
       * Dark mode: on
       */
      on: string
      /**
       * Dark mode: off
       */
      off: string
    }
    /**
     * Logout
     */
    logout: string
  }
  cookie: {
    /**
     * Got it
     */
    button: string
    /**
     * 🍪 This website uses cookies.
     */
    message: string
  }
  rules: {
    /**
     * As soon as you get an actionable task (receive an email, phonecall, text, or if you see anything of interest that has to be put on your todo list) — create a todo for it right away. Do not wait, you will forget about it if you do not take it down.
     */
    '0': string
    /**
     * Todos should always be actionable and as explicit as possible. If a task takes less than 2 minutes, then do it right away and record it as completed.
     */
    '1': string
    /**
     * You either add a specific date or select a month while creating a todo. You cannot pick current month without selecting a specific date. This is done to relax your mind. If you trust the system and put everything that needs to be done on the correct date — you will encounter it at the right time. Huge amount of willpower is wasted on being constantly stressed about "that other thing that I need to deal with but I am not quite sure what it was". Learn to trust and relax.
     */
    '2': string
    /**
     * First thing you do each month is planning ahead. You take all the tasks assigned to the current month and you sort them in the correct dates. It allows you to filter out outdated tasks and keep your mind in peace with, knowing exactly what you need to do this month.
     */
    '3': string
    /**
     * First thing you do in the morning is planning your day. Have a glance at your Planning section. Can you handle everything? Distribute tasks that cannot be dealt with today. Redistribute any tasks left undone from the previous days.
     */
    '4': string
    /**
     * Unless it is an emergency, do not look at the planning section after you have finished planning. It will be way better psychologically if you only focus on one task, so keep your eyes on the Current section. Trust the system, it remembers everything. Do your job and relax your mind.
     */
    '5': string
    /**
     * Current section contains only one task that you need to focus on — nothing else. You can have more than one task a day, the amount of tasks as well as progress bar is displayed for your convenience. You are not allowed to jump between tasks — you should deal with every task linearly, one by one.
     */
    '6': string
    /**
     * Frogs are special types of tasks you generally do not want to deal with. Usually they are the tasks left behind for months and even years. Todorant ensures that you handle frogs first thing every day. In the morning your willpower reserve is large enough to handle even the most outrageous tasks. And after you finally deal with a frog — you receive just enough happiness to be smiling throughout the whole day. You feel proud of yourself when you deal with frogs.
     */
    '7': string
    /**
     * You are allowed to skip current task — but try to do so as rarely as possible. You cannot skip a frog. If you failed to complete a task and had to redistribute it twice, it becomes a frog.
     */
    '8': string
    /**
     * If the current task is too high level, then break it down to a list of subtasks. As soon as you break it down, the task is marked as completed.
     */
    '9': string
    /**
     * Add as much relevant information about the todo as possible. Add links to specific emails (gmail on web allows you to do this), websites, notes (like evernote), documents (like dropbox), leave phone numbers or add any information you might need to complete the task. Todorant is not meant to be a point of reference for you — instead it should act as a catalogue of links to the reference information relevant to specific todos.
     */
    '10': string
    /**
     * Feel free to join our multi-language group on Telegram to share experience and tricks on how to be more productive — @todorant_feedback! Your feedback about the service — suggestions, wishes and complaints — are highly welcome.
     */
    '11': string
    /**
     * Use the edit mode (the list order icon on top) on the Planning page to change the task order. If you want to assign a task to a specific week, just assign it to Monday and reassign it during the planning phase on Monday morning.
     */
    '12': string
    /**
     * Todorant does not have and will never have repeating tasks — the only thing they do well causing anxiety by hanging over you as unfinished tasks. If you need to complete repeating tasks — add all of them manually, your brain will thank you for conscious tasks.
     */
    '13': string
    /**
     * Todorant does not have the concept of "Projects" as it has proven itself to be demotivating, some of the "folder" never get open. Projects "Fitness" and "Self-improvement" send their regards. Instead, use #hashtags.
     */
    '14': string
    /**
     * Frogs will always appear on the top of the list.
     */
    '15': string
    /**
     * Todorant does not have notifications about the upcoming tasks with the exact time set. However, feel free to use Google Calendar integration so that Google can annoy you with notifications, not Todorant.
     */
    '16': string
  }
  howto: {
    /**
     * How to use Todorant?
     */
    title: string
    /**
     * Below are the main principles that you should follow to productively exploit all the features provided by Todorant. It is easy as 1-2-3, just with a few more steps.
     */
    premise: string
    bonus: {
      /**
       * Bonus features
       */
      title: string
      rules: {
        /**
         * Use keyboard shortcuts when on desktop! You can (a)dd, (b)reakdown, switch to (c)urrent, mark as (d)one and switch to (p)lanning. To add an additional task slot while adding tasks, you can use Ctrl+Shift+A.
         */
        '0': string
      }
    }
  }
  /**
   * Intro message
   */
  introButton: string
  feedback: {
    /**
     * What do the users say?
     */
    title: string
    reviews: {
      '0': {
        /**
         * Sergey Romanov
         */
        name: string
        /**
         * Gendoor
         */
        username: string
        /**
				 * Messages in the subscription part are cute :)
			
			Thank you for the simple service thriving for the ideal. Turned out that it not only helps to be productive but also proactive. Little daily improvements confidently enhance life, and the free mind is constantly looking how to fill now emptied todo list so that it could feel the pleasure of completing tasks again and again — and it is a direct route towards improving everything surrounding me.
			
			All in all, Todorant, no matter how simple at first glance, can become a faithful ally in any business. Thank you, Nikita, for unleashing the aspects of true productivity and sharing them with us in a convenient solution.
			
			Thankful Todorant subscriber.
				 */
        text: string
      }
      '1': {
        /**
         * Dinislam Sad
         */
        name: string
        /**
         * Azerzet
         */
        username: string
        /**
				 * The main advantages that I, and I'm sure others, liked.
			1. Simple and convenient interface.
			2. Missed tasks automatically become frogs, and an option to make a task a frog initially.
			3. /done command is a must, and thank you for it, Nikita. I used Todoist, Wunderlist, Bitrix24. All of them are overcomplicated.
			4. Telegram bot.
				 */
        text: string
      }
      '2': {
        /**
         * Aleksei Kaut
         */
        name: string
        /**
         * aleksei_kaut
         */
        username: string
        /**
				 * After I created the first tasks and switched to the 'Current' tab — I was surprised that I had only one task and that I needed to complete it before moving on. This idea with one task and concentration on it struck me, it seems obvious, but I couldn"t use it before.
			
			I usually tracked tasks and ideas in Notes, which should be done soon, but I did not approach it as a system. I have been using the service for a couple of weeks, not very actively, but I think this is a very strong way to systemize the affairs and tasks.
			
			Thank you for your work!
				 */
        text: string
      }
      '3': {
        /**
         * Anton
         */
        name: string
        /**
         * mas1311
         */
        username: string
        /**
				 * Tested Todorant. At first, I was skeptical (I tried a lot of planning services already), but I realized that it works effectively and is very easy to use.
			
			Plus, for reasons unknown to me, when all the tasks are completed for the day, strong satisfaction appears, which was absent in other planners (there was something like 'well, that was everything... or not?').
			
			Thank you for your work!
				 */
        text: string
      }
      '4': {
        /**
         * Willsey Paslen
         */
        name: string
        /**
         * WillseyPaslen
         */
        username: string
        /**
         * Thanks for the great service. Enough time has passed so that I can say — it helps me. Thanks, Nikita 😁 And good luck with the app.
         */
        text: string
      }
      '5': {
        /**
         * Igor Malinkin
         */
        name: string
        /**
         * sxe4kilo
         */
        username: string
        /**
         * I started to do at least something with Todorant, so my productivity went up from 0.
         */
        text: string
      }
      '6': {
        /**
         * Vladimir Dubenko
         */
        name: string
        /**
         * dubenko_v
         */
        username: string
        /**
				 * Your service is awesome in terms of at least three things:
			1. Convenient — it is minimalistic!
			2. It instills a habit.
			3. Strange as it may seem, it doesn't force you to think rationally.
			
			I'm irrational by nature, I can't just lead 1 project (I burn out quickly). My life is multitasking! 3 projects in parallel are easy, but 3 is not enough... 7 sounds more like it. And your service allows you to achieve this. It is the alternation of tasks that prevents the brain from burning out in one particular direction. And somehow, magically, it alternates tasks from one project to another.
				 */
        text: string
      }
      '7': {
        /**
         * Maksim Alekseyevich
         */
        name: string
        /**
         * MMAradiology
         */
        username: string
        /**
				 * I can"t say that using Todorant changed my life. Can I say that this is a meaningful and very useful application/website? Yes, thousand times yes.
			
			I like Todorant, it lets me free up my 'operating memory' and allows me to think about solving problems, not about remembering them. As Nikita (the creator) correctly wrote — with constant and correct use, tasks that used to cast true biblical fear will stop appearing. And this will not happen because the complex tasks will stop coming. It will become clear to you (and to me, and everyone) that 'the road will be overpowered by those walking', 'the way to the thousand miles begins with one step'.
				 */
        text: string
      }
      '8': {
        /**
         * Kiku Reise
         */
        name: string
        /**
         * Kiku_Reise
         */
        username: string
        /**
				 * I've arranged my work, programming and hobby tasks. Even this review was written thanks to Todorant. Just one task, no complications. That's the whole point of the app — it helped me to concentrate without constantly shuffling my todos.
			
			Of course, you can set tasks and forget about them, but for me, it's easier to go back to a minimalistic application with one task, rather than to spend half a day looking for what task to work on now out of a hundred planned in Telegram or Notion.
			
			I was especially pleased with the update with hashtags — now all stats are on the palm of my hand, I can track and share with friends how many tasks I have completed this month.
			
			Thank you a lot for Todorant!
				 */
        text: string
      }
    }
  }
}

export type TranslationFunctions = {
  /**
   * Frontend Template
   */
  title: () => LocalizedString
  /**
   * User count: {{count}}
   */
  userCount: (arg0: string | number | boolean) => LocalizedString
  landingShort: {
    /**
     * Productivity systems fail.
     */
    headline: () => LocalizedString
    /**
     * Todorant works.
     */
    headline2: () => LocalizedString
    /**
     * Focus on one task at a time
     */
    feature1: () => LocalizedString
    /**
     * Always add a date or a month to a task
     */
    feature2: () => LocalizedString
    /**
     * Complete unpleasant tasks (frogs) first
     */
    feature3: () => LocalizedString
    /**
     * Keep your inbox empty
     */
    feature4: () => LocalizedString
    /**
     * What's the difference?
     */
    differenceTitle: () => LocalizedString
    /**
     * All other productivity apps focus on storing, organizing and automating endless lists of tasks. Todorant focuses on the only thing that matters: it makes you complete the tasks.
     */
    differenceText1: () => LocalizedString
    /**
     * Todorant uses a carefully crafted set of limits and praise to punish bad behaviour and support good habits. It affects the primitive part of the brain to make it crave completing todos like people crave sugar.
     */
    differenceText2: () => LocalizedString
    /**
     * I've read and tried 20+ productivity books and methodologies. When all of them failed one by one I combined their components and simplified the result. This is how Todorant was created.
     */
    differenceText3: () => LocalizedString
    /**
     * Truly cross-platform
     */
    crossplatform: () => LocalizedString
    /**
     * What's the deal?
     */
    dealTitle: () => LocalizedString
    /**
     * Todorant is free for the first 30 days and then it is $5/month. It is more expensive than competitors because it works. If you don't get $5 worth of productivity in the first 30 days of the free trial, you are welcome not to continue to use Todorant.
     */
    dealText1: () => LocalizedString
    /**
     * No strings attached. You don't need to give us any information like a credit card at all before your trial ends. You don't even need an account if you install the mobile apps!
     */
    dealText2: () => LocalizedString
    /**
     * The only exception is if you signup on iOS, Apple has forced us to make you commit to a free trial before you can use the app. The way to avoid this limit is to create an account here, on the website, and then log in on the iOS app.
     */
    dealText3: () => LocalizedString
    /**
     * Act!
     */
    act: () => LocalizedString
    contact: {
      /**
       * Still got questions? Contact me directly at
       */
      '0': () => LocalizedString
      /**
       * . Thank you.
       */
      '1': () => LocalizedString
    }
    /**
     * Privacy policy
     */
    privacy: () => LocalizedString
  }
  /**
   * Sign in
   */
  signIn: () => LocalizedString
  menu: {
    darkMode: {
      /**
       * Dark mode: on
       */
      on: () => LocalizedString
      /**
       * Dark mode: off
       */
      off: () => LocalizedString
    }
    /**
     * Logout
     */
    logout: () => LocalizedString
  }
  cookie: {
    /**
     * Got it
     */
    button: () => LocalizedString
    /**
     * 🍪 This website uses cookies.
     */
    message: () => LocalizedString
  }
  rules: {
    /**
     * As soon as you get an actionable task (receive an email, phonecall, text, or if you see anything of interest that has to be put on your todo list) — create a todo for it right away. Do not wait, you will forget about it if you do not take it down.
     */
    '0': () => LocalizedString
    /**
     * Todos should always be actionable and as explicit as possible. If a task takes less than 2 minutes, then do it right away and record it as completed.
     */
    '1': () => LocalizedString
    /**
     * You either add a specific date or select a month while creating a todo. You cannot pick current month without selecting a specific date. This is done to relax your mind. If you trust the system and put everything that needs to be done on the correct date — you will encounter it at the right time. Huge amount of willpower is wasted on being constantly stressed about "that other thing that I need to deal with but I am not quite sure what it was". Learn to trust and relax.
     */
    '2': () => LocalizedString
    /**
     * First thing you do each month is planning ahead. You take all the tasks assigned to the current month and you sort them in the correct dates. It allows you to filter out outdated tasks and keep your mind in peace with, knowing exactly what you need to do this month.
     */
    '3': () => LocalizedString
    /**
     * First thing you do in the morning is planning your day. Have a glance at your Planning section. Can you handle everything? Distribute tasks that cannot be dealt with today. Redistribute any tasks left undone from the previous days.
     */
    '4': () => LocalizedString
    /**
     * Unless it is an emergency, do not look at the planning section after you have finished planning. It will be way better psychologically if you only focus on one task, so keep your eyes on the Current section. Trust the system, it remembers everything. Do your job and relax your mind.
     */
    '5': () => LocalizedString
    /**
     * Current section contains only one task that you need to focus on — nothing else. You can have more than one task a day, the amount of tasks as well as progress bar is displayed for your convenience. You are not allowed to jump between tasks — you should deal with every task linearly, one by one.
     */
    '6': () => LocalizedString
    /**
     * Frogs are special types of tasks you generally do not want to deal with. Usually they are the tasks left behind for months and even years. Todorant ensures that you handle frogs first thing every day. In the morning your willpower reserve is large enough to handle even the most outrageous tasks. And after you finally deal with a frog — you receive just enough happiness to be smiling throughout the whole day. You feel proud of yourself when you deal with frogs.
     */
    '7': () => LocalizedString
    /**
     * You are allowed to skip current task — but try to do so as rarely as possible. You cannot skip a frog. If you failed to complete a task and had to redistribute it twice, it becomes a frog.
     */
    '8': () => LocalizedString
    /**
     * If the current task is too high level, then break it down to a list of subtasks. As soon as you break it down, the task is marked as completed.
     */
    '9': () => LocalizedString
    /**
     * Add as much relevant information about the todo as possible. Add links to specific emails (gmail on web allows you to do this), websites, notes (like evernote), documents (like dropbox), leave phone numbers or add any information you might need to complete the task. Todorant is not meant to be a point of reference for you — instead it should act as a catalogue of links to the reference information relevant to specific todos.
     */
    '10': () => LocalizedString
    /**
     * Feel free to join our multi-language group on Telegram to share experience and tricks on how to be more productive — @todorant_feedback! Your feedback about the service — suggestions, wishes and complaints — are highly welcome.
     */
    '11': () => LocalizedString
    /**
     * Use the edit mode (the list order icon on top) on the Planning page to change the task order. If you want to assign a task to a specific week, just assign it to Monday and reassign it during the planning phase on Monday morning.
     */
    '12': () => LocalizedString
    /**
     * Todorant does not have and will never have repeating tasks — the only thing they do well causing anxiety by hanging over you as unfinished tasks. If you need to complete repeating tasks — add all of them manually, your brain will thank you for conscious tasks.
     */
    '13': () => LocalizedString
    /**
     * Todorant does not have the concept of "Projects" as it has proven itself to be demotivating, some of the "folder" never get open. Projects "Fitness" and "Self-improvement" send their regards. Instead, use #hashtags.
     */
    '14': () => LocalizedString
    /**
     * Frogs will always appear on the top of the list.
     */
    '15': () => LocalizedString
    /**
     * Todorant does not have notifications about the upcoming tasks with the exact time set. However, feel free to use Google Calendar integration so that Google can annoy you with notifications, not Todorant.
     */
    '16': () => LocalizedString
  }
  howto: {
    /**
     * How to use Todorant?
     */
    title: () => LocalizedString
    /**
     * Below are the main principles that you should follow to productively exploit all the features provided by Todorant. It is easy as 1-2-3, just with a few more steps.
     */
    premise: () => LocalizedString
    bonus: {
      /**
       * Bonus features
       */
      title: () => LocalizedString
      rules: {
        /**
         * Use keyboard shortcuts when on desktop! You can (a)dd, (b)reakdown, switch to (c)urrent, mark as (d)one and switch to (p)lanning. To add an additional task slot while adding tasks, you can use Ctrl+Shift+A.
         */
        '0': () => LocalizedString
      }
    }
  }
  /**
   * Intro message
   */
  introButton: () => LocalizedString
  feedback: {
    /**
     * What do the users say?
     */
    title: () => LocalizedString
    reviews: {
      '0': {
        /**
         * Sergey Romanov
         */
        name: () => LocalizedString
        /**
         * Gendoor
         */
        username: () => LocalizedString
        /**
				 * Messages in the subscription part are cute :)
			
			Thank you for the simple service thriving for the ideal. Turned out that it not only helps to be productive but also proactive. Little daily improvements confidently enhance life, and the free mind is constantly looking how to fill now emptied todo list so that it could feel the pleasure of completing tasks again and again — and it is a direct route towards improving everything surrounding me.
			
			All in all, Todorant, no matter how simple at first glance, can become a faithful ally in any business. Thank you, Nikita, for unleashing the aspects of true productivity and sharing them with us in a convenient solution.
			
			Thankful Todorant subscriber.
				 */
        text: () => LocalizedString
      }
      '1': {
        /**
         * Dinislam Sad
         */
        name: () => LocalizedString
        /**
         * Azerzet
         */
        username: () => LocalizedString
        /**
				 * The main advantages that I, and I'm sure others, liked.
			1. Simple and convenient interface.
			2. Missed tasks automatically become frogs, and an option to make a task a frog initially.
			3. /done command is a must, and thank you for it, Nikita. I used Todoist, Wunderlist, Bitrix24. All of them are overcomplicated.
			4. Telegram bot.
				 */
        text: () => LocalizedString
      }
      '2': {
        /**
         * Aleksei Kaut
         */
        name: () => LocalizedString
        /**
         * aleksei_kaut
         */
        username: () => LocalizedString
        /**
				 * After I created the first tasks and switched to the 'Current' tab — I was surprised that I had only one task and that I needed to complete it before moving on. This idea with one task and concentration on it struck me, it seems obvious, but I couldn"t use it before.
			
			I usually tracked tasks and ideas in Notes, which should be done soon, but I did not approach it as a system. I have been using the service for a couple of weeks, not very actively, but I think this is a very strong way to systemize the affairs and tasks.
			
			Thank you for your work!
				 */
        text: () => LocalizedString
      }
      '3': {
        /**
         * Anton
         */
        name: () => LocalizedString
        /**
         * mas1311
         */
        username: () => LocalizedString
        /**
				 * Tested Todorant. At first, I was skeptical (I tried a lot of planning services already), but I realized that it works effectively and is very easy to use.
			
			Plus, for reasons unknown to me, when all the tasks are completed for the day, strong satisfaction appears, which was absent in other planners (there was something like 'well, that was everything... or not?').
			
			Thank you for your work!
				 */
        text: () => LocalizedString
      }
      '4': {
        /**
         * Willsey Paslen
         */
        name: () => LocalizedString
        /**
         * WillseyPaslen
         */
        username: () => LocalizedString
        /**
         * Thanks for the great service. Enough time has passed so that I can say — it helps me. Thanks, Nikita 😁 And good luck with the app.
         */
        text: () => LocalizedString
      }
      '5': {
        /**
         * Igor Malinkin
         */
        name: () => LocalizedString
        /**
         * sxe4kilo
         */
        username: () => LocalizedString
        /**
         * I started to do at least something with Todorant, so my productivity went up from 0.
         */
        text: () => LocalizedString
      }
      '6': {
        /**
         * Vladimir Dubenko
         */
        name: () => LocalizedString
        /**
         * dubenko_v
         */
        username: () => LocalizedString
        /**
				 * Your service is awesome in terms of at least three things:
			1. Convenient — it is minimalistic!
			2. It instills a habit.
			3. Strange as it may seem, it doesn't force you to think rationally.
			
			I'm irrational by nature, I can't just lead 1 project (I burn out quickly). My life is multitasking! 3 projects in parallel are easy, but 3 is not enough... 7 sounds more like it. And your service allows you to achieve this. It is the alternation of tasks that prevents the brain from burning out in one particular direction. And somehow, magically, it alternates tasks from one project to another.
				 */
        text: () => LocalizedString
      }
      '7': {
        /**
         * Maksim Alekseyevich
         */
        name: () => LocalizedString
        /**
         * MMAradiology
         */
        username: () => LocalizedString
        /**
				 * I can"t say that using Todorant changed my life. Can I say that this is a meaningful and very useful application/website? Yes, thousand times yes.
			
			I like Todorant, it lets me free up my 'operating memory' and allows me to think about solving problems, not about remembering them. As Nikita (the creator) correctly wrote — with constant and correct use, tasks that used to cast true biblical fear will stop appearing. And this will not happen because the complex tasks will stop coming. It will become clear to you (and to me, and everyone) that 'the road will be overpowered by those walking', 'the way to the thousand miles begins with one step'.
				 */
        text: () => LocalizedString
      }
      '8': {
        /**
         * Kiku Reise
         */
        name: () => LocalizedString
        /**
         * Kiku_Reise
         */
        username: () => LocalizedString
        /**
				 * I've arranged my work, programming and hobby tasks. Even this review was written thanks to Todorant. Just one task, no complications. That's the whole point of the app — it helped me to concentrate without constantly shuffling my todos.
			
			Of course, you can set tasks and forget about them, but for me, it's easier to go back to a minimalistic application with one task, rather than to spend half a day looking for what task to work on now out of a hundred planned in Telegram or Notion.
			
			I was especially pleased with the update with hashtags — now all stats are on the palm of my hand, I can track and share with friends how many tasks I have completed this month.
			
			Thank you a lot for Todorant!
				 */
        text: () => LocalizedString
      }
    }
  }
}

export type Formatters = {}
